version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/testdeploy3/
permissions:
  - object: /var/www/html/testdeploy3/havas-scripts/restart.sh
    owner: root
    mode: 777
    type:
      - file
hooks:
AfterInstall:
  - location: /havas-scripts/restart-apache.sh
    timeout: 300
    runas: root