version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/testdeploy/
permissions:
  - object: /var/www/html/testdeploy/havas-scripts/restart.sh
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
AfterInstall:
  - location: /havas-scripts/restart-apache.sh
    timeout: 300
    runas: root