version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/testdeploy/
 - object: /var/www/html/havas-scripts/
    pattern: "*.sh"	
    mode: 777
    owner: ec2-user
hooks:
ApplicationStart:
  - location: /havas-scripts/restart-apache.sh
    timeout: 300
    runas: root