version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/testdeploy/
permissions:
  - object: /var/www/html/testdeploy/touchfile.sh
    owner: apache
    group: apache
    mode: 777
    type:
      - file
hooks:

AfterInstall:
  - location: /havas-scripts/touchfile.sh
    timeout: 300
    runas: root