version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/testdeploy2/
permissions:
   - object: /var/www/html/testdeploy2/havas-scripts/restart.sh
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
AfterInstall:
  - location: /havas-scripts/restart-apache.sh
    timeout: 300
    runas: root