version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/testdeploy/
hooks:
  BeforeInstall:
    - location: /var/www/html/testdeploy/touchfile.sh
      timeout: 400
      runas: root